# pubspec.yaml
name: keyboard_shortcut_listener
description: A Flutter package that enables dynamic keyboard shortcut functionality with configurable actions and visibility control.
version: 0.1.0
homepage: https://github.com/yourusername/keyboard_shortcut_listener

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # No specific flutter configuration needed